name: Deploy til preprod

on: [workflow_dispatch]

env:
  IMAGE_BASE_CR: ghcr.io/${{ github.repository }}
  GITHUB_USERNAME: x-access-token
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy-dev:
    name: Deploye til DEV
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2.3.4
      - name: Sette opp Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 12.x
      - name: Installere moduler
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
      - name: Tester og linting
        run: yarn test && yarn less:lint
      - name: Bygge kode
        run: yarn build
      - name: Sette Docker-navn og -tag
        run: |
          echo "TAG=${TAG}$(date +"%Y%m%d%H%M%S")-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE=${IMAGE_BASE_CR}$(cat .docker_image):$(cat .docker_tag)" >> $GITHUB_ENV
      - name: Bygg og laste opp docker-image
        run: |
          docker pull node:alpine
          docker build --tag ${IMAGE_BASE_CR}:${TAG} --tag ${IMAGE_BASE_CR}:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "x-access-token" --password-stdin ghcr.io
          docker push ${IMAGE_BASE_CR} --all-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploye til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.DEPLOY_KEY }}
          CLUSTER: dev-fss
          RESOURCE: deploy/dev-fss.yml
          NAMESPACE: default
          VAR: image=${{ env.IMAGE_BASE_CR }}
