name: Last opp Docker image
on:
  push:
    branches:
      - k9-los-web-inn-i-verdikjede
env:
  IMAGE_BASE: ghcr.io/navikt/k9-los-web-e2e
jobs:
  push-docker-image:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Hente kode
        uses: actions/checkout@v4
      #- uses: navikt/github-app-token-generator@v1
      #  id: get-token
      #  with:
      #    private-key: ${{ secrets.K9SAKSBEHANDLING_PRIVATE_KEY }}
      #    app-id: ${{ secrets.K9SAKSBEHANDLING_APP_ID }}
      - name: Sette Docker-navn og -tag
        run: |
          echo "IMAGE=$IMAGE_BASE:$(date +"%Y%m%d%H%M%S")-$(echo $GITHUB_SHA | cut -c1-7)">> $GITHUB_ENV
      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          tag: 'latest'
          team: k9saksbehandling
          pull: true
          dockerfile: ./e2e/Dockerfile
          docker_context: './e2e'
          image_suffix: 'e2e'
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  trigger-test:
    name: Trigger verdikjede test
    needs: [push-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test
        run: |
          curl -XPOST -u "x-access-token:${{secrets.GH_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/navikt/k9-verdikjede/actions/workflows/build.yml/dispatches \
          -d '{"ref":"master",
                  "inputs":{
                      "trigger": "${{ github.repository }}"
                  }}'
